[mgr]
sort_by = "mtime"
sort_reverse = true
# show_hidden = true

[opener]
edit = [
	{ run = '$EDITOR %s', block = true, for = "unix" },
	{ run = 'nvim %s', block = true, for = "unix" },
	{ run = "%EDITOR% %s",  block = true, for = "windows" },
	{ run = 'zed %s', block = false, orphan = true, for = "unix" },
	{ run = 'code %s', block = false, orphan = true, for = "unix" },
]

view = [
	{ run = 'PAGER=moar glow -p -w 0 %s1', block = true},
	{ run = 'cmux markdown open %s', block = false, orphan = true, for = "unix" }
]

play = [
	{ run = 'mpv %s', orphan = true, for = "unix"},
	{ run = 'ffprobe %s | less', orphan = false, for = "unix", block = true}
]

[open]
prepend_rules = [
	{ url = "*.json", use = "edit" },
	{ url = "*.html", use = [ "open", "edit" ] },
	{ url = "*.csv", use = [ "open", "edit" ] },
	{ url = "*.svg", use = [ "open", "edit" ] },
	{ url = "*.md", use = ["view", "edit"] },
	{ url = "*.m3u8", use = ["play", "edit"] },
]

[[plugin.prepend_previewers]]
url = "*.md"
run  = "cmux-md"

[[plugin.prepend_previewers]]
url = "*.2d"
run  = 'piper -- nu -c "source ~/.config/nushell/autoload/split2d.nu; 2d "$1""'

[[plugin.prepend_previewers]]
url = "*.mermaid"
run = "cmux-browser"

[[plugin.prepend_previewers]]
url = "*.mmd"
run = "cmux-browser"

[[plugin.prepend_previewers]]
url = "*.html"
run = "cmux-browser"

[[plugin.prepend_previewers]]
url = "*.svg"
run = "cmux-browser"
