#theme = material_deep_ocean
#theme = "catppuccin_latte"
theme = "catppuccin_mocha"
# theme = "dracula"


[editor]
# mouse = false
# statusline.right = ["primary-selection-length","spacer","register","spacer","position","separator","total-line-numbers","separator","position-percentage","file-type","file-encoding","file-line-ending"]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
Cmd-s = ":write"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
Y = ":yank-diagnostic"

[keys.normal."space"]
# Lazygit
# could spawn new ghostty tab instead?
i = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

# Opens a new Ghostty tab/window running glow
G = [":sh ghostty -e glow -p \"$PWD/%{buffer_name}\""]

B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"

# Markdown Helpers
t = ["extend_to_line_bounds", ":pipe /Users/naokiiida/.config/helix/toggle_task.sh", ":write"]
p = ":sh open %{buffer_name}"

[keys.select."space"]
c = [":pipe sed 's/^/`/' | sed 's/$/`/'"]
b = [":pipe awk 'BEGIN{print \"```\"} {print} END{print \"```\"}'"]
h = [":pipe sed 's/^/==/;s/$/==/'"]

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.select]
# # Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"

# # Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"
