#theme = material_deep_ocean
#theme = "catppuccin_latte"
#theme = "dracula"
theme = "catppuccin_latte"

[editor]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
